### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by ellisrichardj**
Just updating readme and main.nf to ensure consist naming of the pipeline

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/APHA-CSU/genappdataanalysis/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by televisedbrain — APPROVED** [review]

**Review by praveenmurugan101 — APPROVED** [review]
Looks good🏆

**Review by sainab-omar — APPROVED** [review]
Looks great 👍

**Comment by ellisrichardj** [comment]
I've made some more changes to ensure that tests are passing, especially where I have made changes from away from the very strict nf-core linting.

**Review by sainab-omar — APPROVED** [review]
Looks great - really good to have the tests passing with the changes

**Review by televisedbrain — APPROVED** [review]
Thanks for the update, looks good

**Pull request merged**
